Датасет GARMENTS_WORKING_INDUSTRY

In [53]:
import pandas as pd
df = pd.read_csv('garments_worker_productivity.csv')
df

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,3/11/2015,Quarter2,finishing,Wednesday,10,0.75,2.90,NaN,960,0,0.0,0,0,8.0,0.628333
1193,3/11/2015,Quarter2,finishing,Wednesday,8,0.70,3.90,NaN,960,0,0.0,0,0,8.0,0.625625
1194,3/11/2015,Quarter2,finishing,Wednesday,7,0.65,3.90,NaN,960,0,0.0,0,0,8.0,0.625625
1195,3/11/2015,Quarter2,finishing,Wednesday,9,0.75,2.90,NaN,1800,0,0.0,0,0,15.0,0.505889
1196,3/11/2015,Quarter2,finishing,Wednesday,6,0.70,2.90,NaN,720,0,0.0,0,0,6.0,0.394722

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

In [55]:
df['date'].describe()

count          1197
unique           59
top       1/31/2015
freq             24
Name: date, dtype: object

In [56]:
df['quarter'].describe()

count         1197
unique           5
top       Quarter1
freq           360
Name: quarter, dtype: object

In [57]:
df['department'].describe()

count       1197
unique         3
top       sweing
freq         691
Name: department, dtype: object

In [58]:
df['day'].describe()

count          1197
unique            6
top       Wednesday
freq            208
Name: day, dtype: object

In [59]:
df['wip'].describe()

count      691.000000
mean      1190.465991
std       1837.455001
min          7.000000
25%        774.500000
50%       1039.000000
75%       1252.500000
max      23122.000000
Name: wip, dtype: float64

In [60]:
pd.unique(df['wip']).tolist()

[1108.0,
 nan,
 968.0,
 1170.0,
 984.0,
 795.0,
 733.0,
 681.0,
 872.0,
 578.0,
 668.0,
 861.0,
 772.0,
 913.0,
 1261.0,
 844.0,
 1005.0,
 659.0,
 1152.0,
 1138.0,
 610.0,
 944.0,
 544.0,
 1072.0,
 539.0,
 1278.0,
 1227.0,
 1039.0,
 878.0,
 1033.0,
 782.0,
 1216.0,
 513.0,
 734.0,
 1202.0,
 884.0,
 1255.0,
 1047.0,
 678.0,
 712.0,
 1037.0,
 757.0,
 759.0,
 1083.0,
 666.0,
 1187.0,
 1305.0,
 716.0,
 925.0,
 963.0,
 1101.0,
 1035.0,
 910.0,
 1209.0,
 590.0,
 808.0,
 1179.0,
 1324.0,
 1135.0,
 776.0,
 990.0,
 986.0,
 924.0,
 1120.0,
 1066.0,
 1144.0,
 413.0,
 568.0,
 1189.0,
 942.0,
 1050.0,
 1026.0,
 783.0,
 857.0,
 548.0,
 411.0,
 287.0,
 724.0,
 1122.0,
 970.0,
 1158.0,
 660.0,
 749.0,
 893.0,
 887.0,
 1335.0,
 1082.0,
 1075.0,
 966.0,
 1095.0,
 1383.0,
 1012.0,
 896.0,
 805.0,
 762.0,
 1043.0,
 831.0,
 562.0,
 1208.0,
 1099.0,
 1093.0,
 1031.0,
 1233.0,
 941.0,
 843.0,
 760.0,
 737.0,
 381.0,
 1141.0,
 1004.0,
 581.0,
 1073.0,
 1156.0,
 1211.0,
 1126.0,
 1063.0,
 723.0,
 465.0,
 530.0,
 1297.0,
 715.0,
 1150.0,
 1232.0,
 1218.0,
 1159.0,
 972.0,
 1092.0,
 965.0,
 816.0,
 947.0,
 838.0,
 1086.0,
 1160.0,
 1177.0,
 1281.0,
 1369.0,
 1084.0,
 391.0,
 1102.0,
 1076.0,
 917.0,
 1044.0,
 1067.0,
 1396.0,
 1292.0,
 171.0,
 1128.0,
 865.0,
 825.0,
 1163.0,
 1140.0,
 1027.0,
 1052.0,
 624.0,
 1288.0,
 1381.0,
 882.0,
 1002.0,
 585.0,
 1025.0,
 1028.0,
 1380.0,
 1196.0,
 1006.0,
 930.0,
 938.0,
 1484.0,
 1040.0,
 1492.0,
 1111.0,
 1434.0,
 399.0,
 983.0,
 1134.0,
 1363.0,
 1501.0,
 1352.0,
 1450.0,
 916.0,
 1422.0,
 1206.0,
 1404.0,
 1139.0,
 1735.0,
 1595.0,
 1245.0,
 1720.0,
 1510.0,
 955.0,
 1328.0,
 1384.0,
 1244.0,
 1480.0,
 1863.0,
 1859.0,
 980.0,
 1606.0,
 727.0,
 1472.0,
 1332.0,
 1009.0,
 1266.0,
 1316.0,
 1282.0,
 1382.0,
 1295.0,
 1448.0,
 867.0,
 1636.0,
 1682.0,
 1495.0,
 1181.0,
 1413.0,
 360.0,
 1296.0,
 1217.0,
 532.0,
 1557.0,
 1016.0,
 1584.0,
 1764.0,
 1745.0,
 1250.0,
 1118.0,
 1143.0,
 1337.0,
 1519.0,
 1635.0,
 1299.0,
 1106.0,
 1871.0,
 1294.0,
 1462.0,
 976.0,
 338.0,
 1455.0,
 1559.0,
 1350.0,
 1175.0,
 1868.0,
 1045.0,
 1342.0,
 1340.0,
 1429.0,
 336.0,
 511.0,
 958.0,
 1416.0,
 1287.0,
 1444.0,
 1088.0,
 1579.0,
 1015.0,
 1436.0,
 1601.0,
 717.0,
 830.0,
 1136.0,
 1397.0,
 1116.0,
 1432.0,
 1502.0,
 282.0,
 1417.0,
 799.0,
 1109.0,
 1582.0,
 1124.0,
 1276.0,
 1192.0,
 881.0,
 1400.0,
 16882.0,
 21385.0,
 21266.0,
 21540.0,
 12261.0,
 23122.0,
 8992.0,
 9792.0,
 2984.0,
 839.0,
 2698.0,
 1435.0,
 1500.0,
 1188.0,
 1112.0,
 1452.0,
 340.0,
 1029.0,
 1070.0,
 946.0,
 1639.0,
 415.0,
 1263.0,
 1532.0,
 1094.0,
 1471.0,
 1042.0,
 1248.0,
 326.0,
 1300.0,
 1485.0,
 1069.0,
 766.0,
 557.0,
 1608.0,
 417.0,
 1167.0,
 1186.0,
 1060.0,
 1534.0,
 1142.0,
 1021.0,
 829.0,
 813.0,
 677.0,
 658.0,
 486.0,
 687.0,
 652.0,
 1388.0,
 1615.0,
 1283.0,
 909.0,
 670.0,
 629.0,
 754.0,
 148.0,
 154.0,
 1127.0,
 1506.0,
 1271.0,
 767.0,
 103.0,
 773.0,
 708.0,
 842.0,
 901.0,
 1268.0,
 1546.0,
 1512.0,
 900.0,
 640.0,
 13.0,
 855.0,
 1061.0,
 1498.0,
 598.0,
 656.0,
 854.0,
 609.0,
 788.0,
 667.0,
 11.0,
 434.0,
 1327.0,
 894.0,
 779.0,
 419.0,
 14.0,
 1193.0,
 10.0,
 770.0,
 674.0,
 481.0,
 664.0,
 824.0,
 957.0,
 822.0,
 1420.0,
 679.0,
 507.0,
 814.0,
 700.0,
 919.0,
 1361.0,
 12.0,
 1688.0,
 461.0,
 1079.0,
 895.0,
 912.0,
 784.0,
 7.0,
 680.0,
 1131.0,
 2103.0,
 1445.0,
 1133.0,
 726.0,
 849.0,
 1054.0,
 2120.0,
 179.0,
 741.0,
 685.0,
 864.0,
 1374.0,
 553.0,
 1057.0,
 1587.0,
 868.0,
 1119.0,
 962.0,
 265.0,
 859.0,
 276.0,
 899.0,
 247.0,
 653.0,
 1603.0,
 444.0,
 841.0,
 1410.0,
 1103.0,
 922.0,
 1055.0,
 1146.0,
 746.0,
 834.0,
 1717.0,
 1041.0,
 1531.0,
 627.0,
 450.0,
 891.0,
 541.0,
 709.0,
 1100.0,
 826.0,
 577.0,
 1228.0,
 1641.0,
 1583.0,
 1062.0,
 739.0,
 698.0,
 1172.0,
 408.0,
 1068.0,
 1834.0,
 1085.0,
 323.0,
 1053.0,
 786.0,
 1003.0,
 635.0,
 847.0,
 361.0,
 1653.0,
 15.0,
 694.0,
 1065.0,
 1020.0,
 1591.0,
 398.0,
 437.0,
 1164.0,
 954.0,
 1194.0,
 644.0,
 792.0,
 512.0,
 556.0,
 622.0,
 549.0,
 1393.0,
 1578.0,
 254.0,
 347.0,
 692.0,
 934.0,
 1527.0,
 632.0,
 1231.0,
 616.0,
 551.0,
 935.0,
 832.0,
 1511.0,
 601.0,
 1562.0,
 29.0,
 950.0,
 534.0,
 1096.0,
 402.0,
 573.0,
 1313.0,
 157.0,
 433.0,
 961.0,
 1169.0,
 874.0,
 1772.0,
 586.0,
 1334.0,
 30.0,
 261.0,
 52.0,
 455.0,
 797.0,
 959.0,
 1373.0,
 1117.0,
 230.0,
 1390.0,
 529.0,
 1267.0,
 1195.0,
 471.0,
 1226.0,
 1251.0,
 626.0,
 1379.0,
 1254.0,
 1064.0,
 313.0,
 1239.0,
 928.0,
 869.0,
 711.0,
 1322.0,
 964.0,
 1132.0,
 357.0,
 817.0,
 1576.0,
 1262.0,
 953.0,
 1161.0,
 1574.0,
 1104.0,
 756.0,
 1499.0,
 1247.0,
 923.0,
 1180.0,
 1001.0,
 1017.0,
 470.0,
 735.0,
 560.0,
 1674.0,
 290.0,
 971.0,
 992.0,
 914.0]

In [61]:
df.drop('wip', axis=1, inplace=True)

In [62]:
df.drop('date', axis=1, inplace=True)
df.drop('day', axis=1, inplace=True)

In [63]:
df = pd.concat([df, pd.get_dummies(df.quarter)], axis=1)

In [64]:
df = pd.concat([df, pd.get_dummies(df.department)], axis=1)

In [65]:
# df = pd.concat([df, pd.get_dummies(df.day)], axis=1)

In [66]:
df.drop('quarter', axis=1, inplace=True)

In [67]:
df.drop('department', axis=1, inplace=True)

In [68]:
# df.drop('day', axis=1, inplace=True)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   team                   1197 non-null   int64
 1   targeted_productivity  1197 non-null   float64
 2   smv                    1197 non-null   float64
 3   over_time              1197 non-null   int64
 4   incentive              1197 non-null   int64
 5   idle_time              1197 non-null   float64
 6   idle_men               1197 non-null   int64
 7   no_of_style_change     1197 non-null   int64
 8   no_of_workers          1197 non-null   float64
 9   actual_productivity    1197 non-null   float64
 10  Quarter1               1197 non-null   uint8
 11  Quarter2               1197 non-null   uint8
 12  Quarter3               1197 non-null   uint8
 13  Quarter4               1197 non-null   uint8
 14  Quarter5               1197 non-null   uint8
 15  finishing              1197 non-null   uint8
 16  finishing              1197 non-null   uint8
 17  sweing                 1197 non-null   uint8
dtypes: float64(5), int64(5), uint8(8)
memory usage: 103.0 KB

In [70]:
y = df.pop('actual_productivity')
y

0       0.940725
1       0.886500
2       0.800570
3       0.800570
4       0.800382
          ...
1192    0.628333
1193    0.625625
1194    0.625625
1195    0.505889
1196    0.394722
Name: actual_productivity, Length: 1197, dtype: float64

In [71]:
x = df

In [72]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   team                   1197 non-null   int64
 1   targeted_productivity  1197 non-null   float64
 2   smv                    1197 non-null   float64
 3   over_time              1197 non-null   int64
 4   incentive              1197 non-null   int64
 5   idle_time              1197 non-null   float64
 6   idle_men               1197 non-null   int64
 7   no_of_style_change     1197 non-null   int64
 8   no_of_workers          1197 non-null   float64
 9   Quarter1               1197 non-null   uint8
 10  Quarter2               1197 non-null   uint8
 11  Quarter3               1197 non-null   uint8
 12  Quarter4               1197 non-null   uint8
 13  Quarter5               1197 non-null   uint8
 14  finishing              1197 non-null   uint8
 15  finishing              1197 non-null   uint8
 16  sweing                 1197 non-null   uint8
dtypes: float64(4), int64(5), uint8(8)
memory usage: 93.6 KB

In [73]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)

In [74]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [75]:
from sklearn.metrics import r2_score
y_predict = lr.predict(x)
r2_score(y, y_predict)

0.2989850049717625

In [76]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
pl = Pipeline([
    ('poly', PolynomialFeatures(degree=5)),
    ('clf', LinearRegression())
])
pl.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('poly',
                 PolynomialFeatures(degree=5, include_bias=True,
                                    interaction_only=False, order='C')),
                ('clf',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [80]:
y_predict_pl = pl.predict(x)
r2_score(y, y_predict_pl)

-355.3242450275004

In [78]:
from sklearn.model_selection import GridSearchCV
params = [{
    'poly__degree': range(1, 7)
}]
gs = GridSearchCV(pl, params, cv=5)
gs.fit(x_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('poly',
                                        PolynomialFeatures(degree=5,
                                                           include_bias=True,
                                                           interaction_only=False,
                                                           order='C')),
                                       ('clf',
                                        LinearRegression(copy_X=True,
                                                         fit_intercept=True,
                                                         n_jobs=None,
                                                         normalize=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'poly__degree': range(1, 7)}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [79]:
y_p_gs = gs.predict(x)
r2_score(y, y_p_gs)

0.29898500497175784

In [81]:
gs.best_estimator_

Pipeline(memory=None,
         steps=[('poly',
                 PolynomialFeatures(degree=1, include_bias=True,
                                    interaction_only=False, order='C')),
                ('clf',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)